# Generated by Django 4.2 on 2023-07-16 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_alter_rangetime_available_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('state', models.CharField(choices=[('Đang chờ xử lí', 'Đang chờ xử lí'), ('Bài post của bạn không hợp lệ', 'Bài post của bạn không hợp lệ'), ('Đã xử lí, bài post của bạn đã đăng lên bảng tin', 'Đã xử lí, bài post của bạn đã đăng lên bảng tin'), ('Gia sư và bạn đã liên hệ với nhau thành công', 'Gia sư và bạn đã liên hệ với nhau thành công'), ('Gia sư đã dạy xong môn học bạn yêu cầu', 'Gia sư đã dạy xong môn học bạn yêu cầu')], default='Đang chờ xử lí', max_length=100)),
                ('approve_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve_user', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('teaching_address', models.CharField(max_length=150)),
                ('fee', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestTeaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_learner', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=post.models.Post, to='post.post')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('t_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_edited', models.BooleanField(default=False)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_review', to='post.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.postdetail'),
        ),
        migrations.AddField(
            model_name='post',
            name='range_times',
            field=models.ManyToManyField(to='common.rangetime'),
        ),
        migrations.AddField(
            model_name='post',
            name='subjects',
            field=models.ManyToManyField(to='common.subject'),
        ),
        migrations.AddField(
            model_name='post',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AppliedTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('t_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=post.models.Post, to='post.post')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
