# Generated by Django 4.2 on 2023-08-06 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdetail',
            old_name='fee',
            new_name='teaching_fee',
        ),
        migrations.RemoveField(
            model_name='postdetail',
            name='content',
        ),
        migrations.RemoveField(
            model_name='postdetail',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='postdetail',
            name='title',
        ),
        migrations.AddField(
            model_name='postdetail',
            name='leaner_birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postdetail',
            name='leaner_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdetail',
            name='leaner_sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdetail',
            name='request_teacher_education',
            field=models.CharField(blank=True, choices=[('Tốt nghiệp lớp 12', 'Tốt nghiệp lớp 12'), ('Sinh Viên', 'Sinh Viên'), ('Cử Nhân/Kỹ Sư', 'Cử Nhân/Kỹ Sư'), ('Học Viên Cao Học', 'Học Viên Cao Học'), ('Thạc Sĩ', 'Thạc Sĩ'), ('Nghiên cứu sinh', 'Nghiên cứu sinh'), ('Tiến Sĩ', 'Tiến Sĩ'), ('Phó Giáo Sư', 'Phó Giáo Sư'), ('Giáo Sư', 'Giáo Sư')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postdetail',
            name='request_teacher_teaching_exp',
            field=models.CharField(blank=True, choices=[('1 năm', '1 năm'), ('2 năm', '2 năm'), ('3 năm', '3 năm'), ('4 năm', '4 năm'), ('5 năm', '5 năm'), ('Trên 5 năm', 'Trên 5 năm')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postdetail',
            name='request_teacher_working_exp',
            field=models.CharField(blank=True, choices=[('1 năm', '1 năm'), ('2 năm', '2 năm'), ('3 năm', '3 năm'), ('4 năm', '4 năm'), ('5 năm', '5 năm'), ('Trên 5 năm', 'Trên 5 năm')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postdetail',
            name='reuqest_teacher_sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdetail',
            name='reuqest_teacher_year_old_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postdetail',
            name='reuqest_teacher_year_old_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postdetail',
            name='teaching_fee_unit',
            field=models.CharField(choices=[('Tháng', 'Tháng'), ('Tuần', 'Tuần'), ('Buổi', 'Buổi')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdetail',
            name='teaching_location',
            field=models.CharField(choices=[('learner home', 'Nhà người học'), ('teacher home', 'Nhà giáo viên'), ('online', 'Online'), ('leaner home hibrid', 'Nhà người học và online'), ('teacher home hibrid', 'Nhà giáo viên và online')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdetail',
            name='total_teaching_time',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdetail',
            name='total_teaching_time_unit',
            field=models.CharField(choices=[('Tháng', 'Tháng'), ('Tuần', 'Tuần'), ('Buổi', 'Buổi')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
