# Generated by Django 4.2 on 2023-08-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststatus',
            name='state',
            field=models.CharField(choices=[('created', 'Tạo bài thành công'), ('suspended', 'Bài tuyển tạm ngưng'), ('verified', 'Bài đã được duyệt'), ('invalid', 'Bài tuyển bị không hợp lệ'), ('edited', 'Bài tuyển đã chỉnh sửa'), ('teacher_selected', 'Đã chọn được giáo viên'), ('learner_request', 'Học viên mời dạy'), ('teacher_accepted', 'Giáo viên đã đồng ý'), ('teacher_rejected ', 'Giáo viên đã từ chối'), ('connected', 'Đã kết nối giáo viên và học viên')], default='created', max_length=100),
        ),
    ]
