# Generated by Django 4.2 on 2023-08-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_administrativeunits'),
        ('post', '0006_alter_poststatus_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='teaching_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_district', to='common.administrativeunits'),
        ),
        migrations.AddField(
            model_name='post',
            name='teaching_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_province', to='common.administrativeunits'),
        ),
        migrations.AddField(
            model_name='post',
            name='teaching_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_ward', to='common.administrativeunits'),
        ),
        migrations.AlterField(
            model_name='postdetail',
            name='teaching_location',
            field=models.CharField(choices=[('learner_home', 'Nhà người học'), ('teacher_home', 'Nhà giáo viên'), ('online', 'Online'), ('leaner_home_hibrid', 'Nhà người học và online'), ('teacher_home_hibrid', 'Nhà giáo viên và online')], max_length=20),
        ),
    ]
