# Generated by Django 4.2 on 2023-05-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangetime',
            name='available_day',
            field=models.CharField(choices=[('mon', 'Thứ 2'), ('tue', 'Thứ 3'), ('wed', 'Thứ 4'), ('thu', 'Thứ 5'), ('fri', 'Thứ 6'), ('sat', 'Thứ 7'), ('sun', 'Chủ Nhật')], max_length=50),
        ),
    ]
