# Generated by Django 4.2 on 2023-08-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_rangetime_available_day_rangetime_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('codename', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('division_type', models.CharField(choices=[('province', 'province'), ('district', 'district'), ('ward', 'ward')], max_length=50)),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.administrativeunits')),
            ],
        ),
    ]
