# Generated by Django 4.2 on 2023-05-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
