# Generated by Django 4.2 on 2023-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_rangetime_available_day"),
        ("user", "0002_customuser_auth_facebook_customuser_facebook_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_validate_phone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subjects",
            field=models.ManyToManyField(to="common.subject"),
        ),
    ]
