# Generated by Django 4.2 on 2023-08-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_is_validate_phone_customuser_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('any', 'any')], max_length=6, null=True),
        ),
    ]
